

create database retail_sales;
use retail_sales;

create table retail_table(
transactions_id int primary key,
sale_date date,
sale_time time,
customer_id int,
gender varchar(10),
age int,
category varchar(20),
quantiy int,
price_per_unit int,
cogs float,
total_sale float
);

select * from retail_table;

-- HOW MANY RECORDS IN THIS DATASET --
select count(*) from retail_table;


-- CHECKING THE NULL VALUES AND DATA CLEANING --
SELECT * FROM retail_table
WHERE 
TRANSACTIONS_ID IS NULL
OR
SALE_DATE IS NULL
OR
SALE_TIME IS NULL
OR
CUSTOMER_ID IS NULL
OR
GENDER IS NULL
OR
AGE IS NULL
OR
CATEGORY IS NULL 
OR
QUANTIY IS NULL
OR
PRICE_PER_UNIT
OR
COGS IS NULL
OR
TOTAL_SALE IS NULL ;

-- DATA EXPLORATION --

 -- HOW MANY SALES WE HAVE? --
 
 SELECT COUNT(*) AS TOTAL_SALES FROM retail_table; 
 
 -- HOW MANY UNIQUE CUSTOMERS WE HAVE ? --
 
 SELECT COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_CUSTOMERS FROM RETAIL_TABLE;
 
 -- HOW MANY UNIQUE CATAGORY WE HAVE? --
 
 SELECT COUNT(DISTINCT CATEGORY) AS CATEGORY FROM RETAIL_TABLE;
 
 SELECT DISTINCT CATEGORY FROM RETAIL_TABLE;
 
 -- DATA ANALYSIS AND BUSINESS KEY PROBLEMS --
 
 -- My Analysis & Findings --
 
 -- Q.1 WRITE A SQL QUERY TO RETRIEVE ALL COLUMNS FOR SALES MADE ON '2022-11-05'----------------------------------------------------

SELECT * FROM RETAIL_TABLE 
WHERE SALE_DATE = "2022-11-05";

SELECT COUNT(*) FROM RETAIL_TABLE 
WHERE SALE_DATE = "2022-11-05";

-- TOTAL 11 SALES THAT DATE--

/* Q.2 WRITE A SQL QUERY TO RETRIEVE ALL TRANSACTIONS WHERE THE CATEGORY IS 'CLOTHING' AND THE QUANTITY SOLD IS MORE THAN 10 
IN THE MONTH OF NOV-2022 */

-- ONLY THIS MONTH SOLD BY < 10 SO  NO MORE THEN 4 QUANTITY SOLD 

SELECT * FROM RETAIL_TABLE
WHERE CATEGORY = "Clothing"
AND QUANTITY >= 4
AND SALE_DATE >= "2022-11-01"
AND SALE_DATE < "2022-12-01";

-- Q.3 WRITE A SQL QUERY TO CALCULATE THE TOTAL SALES (TOTAL_SALE) FOR EACH CATEGORY

SELECT 
CATEGORY,
SUM(TOTAL_SALE) AS TOTAL_SALES_BY_EACH_CATEGORY,
COUNT(*) AS COUNT_OF_SALES
FROM RETAIL_TABLE
GROUP BY CATEGORY;

-- WRITE A SQL QUERY TO FIND THE AVERAGE AGE OF CUSTOMERS WHO PURCHASED ITEMS FROM THE 'BEAUTY' CATEGORY-------------------

SELECT AVG(AGE) AS AVERAGE_AGE
FROM RETAIL_TABLE
WHERE CATEGORY = "Beauty";

-- WRITE A SQL QUERY TO FIND ALL TRANSACTIONS WHERE THE TOTAL_SALE IS GREATER THAN 1000--------------------------------------

SELECT * FROM RETAIL_TABLE
WHERE TOTAL_SALE > 1000 ;

-- WRITE A SQL QUERY TO FIND THE TOTAL NUMBER OF TRANSACTIONS (TRANSACTION_ID) MADE BY EACH GENDER IN EACH CATEGORY-------------------

SELECT 
CATEGORY,
GENDER,
COUNT(*) AS TOTAL_TRANSACTION
FROM RETAIL_TABLE
GROUP BY CATEGORY, GENDER
ORDER BY CATEGORY, GENDER;

-- WRITE A SQL QUERY TO CALCULATE THE AVERAGE SALE FOR EACH MONTH. FIND OUT BEST SELLING MONTH IN EACH YEAR---------
 
 SELECT 
 YEAR(SALE_DATE) AS YEAR,
 MONTH(SALE_DATE) AS MONTH,
 AVG(TOTAL_SALE) AS AVERAGE_SALE
 FROM RETAIL_TABLE
 GROUP BY 
 YEAR(SALE_DATE),
 MONTH(SALE_DATE)
 ORDER BY 
YEAR(SALE_DATE) DESC ,
MONTH(SALE_DATE) DESC;
 
-- WRITE A SQL QUERY TO FIND THE TOP 5 CUSTOMERS BASED ON THE HIGHEST TOTAL SALES----------------------------------------------------

SELECT 
CUSTOMER_ID,
SUM(TOTAL_SALE) AS HIGEST_SALE
FROM RETAIL_TABLE
GROUP BY CUSTOMER_ID
ORDER BY HIGEST_SALE DESC
LIMIT 5;

-- WRITE A SQL QUERY TO FIND THE NUMBER OF UNIQUE CUSTOMERS WHO PURCHASED ITEMS FROM EACH CATEGORY---------------

SELECT
CATEGORY,
COUNT(DISTINCT CUSTOMER_ID) AS UNIQUE_CUSTOMERS
FROM RETAIL_TABLE
GROUP BY CATEGORY; 

-- WRITE A SQL QUERY TO CREATE EACH SHIFT AND NUMBER OF ORDERS (MORNING <= 12, AFTERNOON BETWEEN 12 & 17 ,EVENING > 17)
SELECT
    CASE
        WHEN HOUR(SALE_TIME) <= 12 THEN 'MORNING'
        WHEN HOUR(SALE_TIME) <= 17 THEN 'AFTERNOON'
        ELSE 'EVENING'
    END AS SHIFT,
    COUNT(TRANSACTIONS_ID) AS NUMBER_OF_ORDERS
FROM RETAIL_TABLE
GROUP BY
    CASE
        WHEN HOUR(SALE_TIME) <= 12 THEN 'MORNING'
        WHEN HOUR(SALE_TIME) <= 17 THEN 'AFTERNOON'
        ELSE 'EVENING'
    END;
    
SELECT * FROM RETAIL_TABLE;

-- ----------------------------------------------  END OF THE PROJECT -----------------------------------------------------------------
